version: 2
updates:
- package-ecosystem: gradle
  directory: /kotlin
  open-pull-requests-limit: 25
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  open-pull-requests-limit: 25
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: /python
  open-pull-requests-limit: 25
  schedule:
    interval: weekly
